baseurl = "https://www.gerhardgroenewald.co.uk/"
DefaultContentLanguage = "en"
title = "Gerhard Groenewald"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClassic = true
pygmentOptions = "linenos=inline"
disqusShortname = "gerhard-groenewald"
googleAnalytics = "UA-123174058-1"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Params]
# homeTitle = "Gerhard Groenewald" # Set a different text for the header on the home page
  subtitle = "management consultant & data scientist"
  logo = "img/beard_icon.jpg"
  favicon = "img/favicon.ico"
  dateFormat = "2 Jan 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  socialShare = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Gerhard Groenewald"
  website = "anjurad.com"
  email = "gerhard@anjurad.com"
  github = "anjurad"
  twitter = "anjurad"
  linkedin = "gerhardgroenewald"
  stackoverflow = "users/6673733/anjurad"
  #youtube = "user/anjurad" # or channel/channelname

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 2
    
[[menu.main]]
    name = "Resume"
    url = "page/resume/"
    weight = 3
    
[[menu.main]]
    name = "Resources"
    url = "page/resources/"
    weight = 4

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 5