---
title: Sabbatical
author: Gerhard Groenewald
date: '2019-04-30'
slug: sabbatical
categories: []
tags: ['data-science', 'management', 'learning']
subtitle: 'an exhaustive review of data science fundamentals'
comments: yes
---

During the last eight years, I spent considerable time analysing data, with a focus on prediction and inference.  It naturally led me to the [emerging *Data Science* field](https://www.forbes.com/sites/gilpress/2013/05/28/a-very-short-history-of-data-science/)
which, at the same time, had been exploding with powerful and accessible tools and techniques.

Using an increasingly broader and more advanced range of solutions ultimately fuelled my a thirst to gain more extensive and in-depth knowledge in [all crucial aspects of the discipline](/page/resources).

In November 2018 my contract ended with Vodafone.  It was an excellent opportunity to take some time out and study all the subjects and specialisations to the level that I had set out to achieve.

I am delighted to announce that I have now completed this journey, one that started many years ago.<br><br>

Data Science is a vast and fast evolving field with many disciplines.  It is therefore by no means the end of my education.  It is merely the start, albeit on a solid footing though.<br><br><hr><br>

### What have I been up to?<br>
I've been busy with quite a bit, but would like to highlight the following aspects:<br><br>

- **Mathematics for Machine Learning**<br>
I did not read mathematics at university even though majoring in highly numerate subjects like Statistical Marketing Research and Financial Management.<br><br>
I wanted a fundamental understanding of algorithms and completed [Mathematics for Machine Learning by Imperial College London on Coursera](https://www.coursera.org/specializations/mathematics-machine-learning).<br><br>

- **Statistics & Probability**<br>
I studied statistics many years ago and wanted to refresh my knowledge and update my toolbag.   I did a refresher in statistics and probability, focussing specifically on using programming libraries to perform statistical calculations and tests and to review aspects that haven't really used and thus forgotten.<br><br>

- **Machine Learning**<br>
[An Introduction to Statistical Learning](http://www-bcf.usc.edu/~gareth/ISL/book.html) is considered by many as the bible of machine learning.  It covers some of the most important modelling and prediction techniques.  The knowledge is transferable even though its application is in R.<br><br>
I studied the book a few years ago and fancied doing the associated online course at some point.  Earlier this year I completed the online course [Statistical Learning, by Stanford University](https://lagunita.stanford.edu/courses/HumanitiesSciences/StatLearning/Winter2016/about) **with distinction**.<br><br>
I supercharged my insight further by working through several books on *building machine learning algorithms from scratch*.[^1]<br><br>

- **Big data**<br>
[Big data is the future.](/post/2018-07-24-first-post)  Up to now, I've not needed big data technologies for my work because both Python and R can be manipulated to work with reasonably large datasets.<br><br>
I've decided to focus on [Spark](https://spark.apache.org) rather than the more mature [Hadoop MapReduce](http://hadoop.apache.org).  I occasionally use [SparklyR](https://spark.rstudio.com) mainly because it is a doddle to set up locally within the RStudio IDE, making it easy to experiment with and learn.  I decided to focus more on the Python ecosystem and completed a few courses in [PySpark](https://spark.apache.org/docs/0.9.1/python-programming-guide.html).<br><br>

For those interested in data science, I am maintaining a [page with a high-level outline of the process and associated resources](/page/resources).

**I am now available for Management Consultant | Data Scientist roles.  Please [get in touch](https://www.linkedin.com/in/gerhardgroenewald/) if you need my help.**

[^1]: <sub>A couple of excellent resources include:<br>
['Data Science from Scratch'](https://www.amazon.co.uk/Data-Science-Scratch-Principles-Python/dp/149190142X) by [Joel Grus](https://joelgrus.com) and ['Machine Learning Algorithms From Scratch'](https://machinelearningmastery.com/machine-learning-algorithms-from-scratch/) by [Jason Brownlee](https://machinelearningmastery.com/about/).</sub>
